### ISSUE TITLE
Android - Small size chrome

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/portfolio#14]
(portfolio page) portfolio images in execution section are not full sized (are full sized in a slightly larger size) 

logo doesn't show up on home page

**Comment by sky-bones** [comment]
logo - was missing slash (fixed)

**Comment by sky-bones** [comment]
At a certain size, the images in work snap to the left, and it's only on certain sizes, (not super consistent)  

<img width="477" alt="screen shot 2015-11-07 at 8 18 08 pm" src="https://cloud.githubusercontent.com/assets/6333963/11018206/aff14958-858c-11e5-9e10-ab7394495498.png">

When resizing the browser, it starts at about 370px. 

The second issue is the second group of images. It has a space that literally doesn't exist.  

<img width="603" alt="screen shot 2015-11-07 at 8 20 00 pm" src="https://cloud.githubusercontent.com/assets/6333963/11018213/f0ae46da-858c-11e5-97a2-b6234f34255f.png">

Both of these bugs are in the _layouts - portfolio-layout page. 

@thomasjbradley

**Comment by thomasjbradley** [comment]
_RE: image sizing_

It could be that there is a `<div>` here that's separating the units from their grid. The only elements that can be directly inside a grid can be units, so it's possible that this is causing the layout issues because the units aren't able to do what they're supposed to.

https://github.com/sky-bones/portfolio/blob/gh-pages/_layouts/portfolio-layout.html#L54

---

_RE: image bottom space_

My first thought was not having `display: block` on the `<img>` tags but that's not the case. I could also be the same problem as above.

**Comment by sky-bones** [comment]
Deleting both of those "process-large" div's fixed it!
